name: "Nix build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v11
      with:
        name: antares
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build -L
    - run: nix flake check
